package ui

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"git.mark1708.ru/me/tmh/internal/config"
	"git.mark1708.ru/me/tmh/internal/i18n"
	"git.mark1708.ru/me/tmh/internal/ui/toast"
	"git.mark1708.ru/me/tmh/internal/xdg"

	"github.com/charmbracelet/lipgloss"
	"gopkg.in/yaml.v3"

	tea "github.com/charmbracelet/bubbletea"
)

// saveCmd returns a tea.Cmd that persists all pending settings to disk.
func (s *settingsModel) saveCmd() tea.Cmd {
	// Snapshot field state by value (fields are small structs).
	fields := s.fields
	cfgPath := s.configPath

	return func() tea.Msg {
		cfg, err := config.Load(cfgPath)
		if err != nil {
			cfg = &config.Config{Version: 1}
			_ = os.MkdirAll(filepath.Dir(cfgPath), 0o755)
		}
		if cfg.Node == nil {
			cfg.Node = minimalConfigNode()
		}

		if ferrs := applyFieldsToConfig(cfg.Node, fields); len(ferrs) > 0 {
			return toastMsg{Kind: toast.KindError, Text: "save: " + ferrs[0].Error()}
		}
		if err := config.Write(cfg, cfgPath, config.WriteOptions{PreserveBlanks: true}); err != nil {
			return toastMsg{Kind: toast.KindError, Text: "save: " + err.Error()}
		}

		if err := writeTmuxConf(fields[catTmux]); err != nil {
			return toastMsg{Kind: toast.KindError, Text: "tmux.conf: " + err.Error()}
		}

		return toastMsg{Kind: toast.KindSuccess, Text: i18n.T("tui.settings.saved")}
	}
}

// applyFieldsToConfig writes all save-then-apply field values into the
// YAML node tree. Returns accumulated non-fatal errors.
func applyFieldsToConfig(root *yaml.Node, fields [numSettingsCats][]settingsField) []error {
	var errs []error
	pset := func(path, val string) {
		if err := config.PathSet(root, path, val); err != nil {
			errs = append(errs, err)
		}
	}
	pbool := func(path string, val bool) {
		if err := config.PathSetBool(root, path, val); err != nil {
			errs = append(errs, err)
		}
	}
	pint := func(path string, val int) {
		if err := config.PathSetInt(root, path, val); err != nil {
			errs = append(errs, err)
		}
	}

	// Display
	if df := fields[catDisplay]; len(df) >= 4 {
		pbool("defaults.display.show_processes_in_tree", df[0].on)
		pbool("defaults.display.show_footer_heatmap", df[1].on)
		pint("defaults.display.preview_default_pane", df[2].chosen)
		pset("defaults.display.tree_density", df[3].choices[df[3].chosen])
	}

	// History (skip read-only index 1 and button index 4)
	if hf := fields[catHistory]; len(hf) >= 5 {
		pset("defaults.history.retention", hf[0].choices[hf[0].chosen])
		pbool("defaults.history.auto_clear_on_startup", hf[2].on)
		pbool("defaults.history.archive_on_clear", hf[3].on)
	}

	// Marks
	if mf := fields[catMarks]; len(mf) >= 1 {
		pbool("defaults.marks.persist_across_sessions", mf[0].on)
	}

	// Tmux
	if tf := fields[catTmux]; len(tf) >= 6 {
		pset("defaults.tmux_integration.default_terminal", tf[0].choices[tf[0].chosen])
		pint("defaults.tmux_integration.escape_time_ms", atoi(tf[1].choices[tf[1].chosen]))
		pbool("defaults.tmux_integration.mouse_mode", tf[2].on)
		pbool("defaults.tmux_integration.status_right_integration", tf[3].on)
		pint("defaults.tmux_integration.base_index", atoi(tf[4].choices[tf[4].chosen]))
		pint("defaults.tmux_integration.pane_base_index", atoi(tf[5].choices[tf[5].chosen]))
	}

	// Behaviour
	if bf := fields[catBehaviour]; len(bf) >= 4 {
		pset("defaults.behaviour.auto_refresh_interval", bf[0].choices[bf[0].chosen])
		pbool("defaults.behaviour.dry_run_default", bf[1].on)
		pbool("defaults.behaviour.confirm_on_kill", bf[2].on)
		pbool("defaults.behaviour.optimistic_rendering", bf[3].on)
	}

	return errs
}

// writeTmuxConf atomically writes the tmh-managed tmux include-file.
func writeTmuxConf(tf []settingsField) error {
	if len(tf) < 6 {
		return nil
	}
	confPath := xdg.TmuxConfPath()
	if err := os.MkdirAll(filepath.Dir(confPath), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(confPath), ".tmux.conf.tmp.*")
	if err != nil {
		return err
	}
	removeTmp := true
	defer func() {
		if removeTmp {
			_ = os.Remove(tmp.Name())
		}
	}()

	w := bufio.NewWriter(tmp)
	_, _ = fmt.Fprintf(w, "# Generated by tmh settings — do not edit manually.\n")
	_, _ = fmt.Fprintf(w, "# Add to ~/.tmux.conf: source-file %s\n\n", confPath)
	_, _ = fmt.Fprintf(w, "set -g default-terminal %q\n", tf[0].choices[tf[0].chosen])
	_, _ = fmt.Fprintf(w, "set -sg escape-time %s\n", tf[1].choices[tf[1].chosen])
	if tf[2].on {
		_, _ = fmt.Fprintln(w, "set -g mouse on")
	} else {
		_, _ = fmt.Fprintln(w, "set -g mouse off")
	}
	_, _ = fmt.Fprintf(w, "set -g base-index %s\n", tf[4].choices[tf[4].chosen])
	_, _ = fmt.Fprintf(w, "setw -g pane-base-index %s\n", tf[5].choices[tf[5].chosen])
	if tf[3].on {
		_, _ = fmt.Fprintln(w, "set -ag status-right ' #(tmh status)'")
	}

	if err := w.Flush(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	_ = tmp.Close()
	removeTmp = false
	return os.Rename(tmp.Name(), confPath)
}

// minimalConfigNode returns a bare YAML document node suitable for a new file.
func minimalConfigNode() *yaml.Node {
	doc := &yaml.Node{Kind: yaml.DocumentNode}
	doc.Content = []*yaml.Node{
		{Kind: yaml.MappingNode, Tag: "!!map"},
	}
	return doc
}

// atoi converts a decimal string to int; returns 0 on any error.
func atoi(s string) int {
	n := 0
	for _, c := range s {
		if c < '0' || c > '9' {
			return 0
		}
		n = n*10 + int(c-'0')
	}
	return n
}

// ── View ────────────────────────────────────────────────────────────────────

func (s *settingsModel) View() string {
	w := s.contentWidth()
	const catW = 17
	sepChar := "│"
	rightW := w - catW - len(sepChar)
	if rightW < 12 {
		rightW = 12
	}

	p := s.st.Palette
	mb := modalBg(p)
	title := s.st.Title.Inherit(mb)
	hint := s.st.Hint.Inherit(mb)

	var b strings.Builder

	// Title row
	titleText := s.str.Settings.Title
	if s.dirty {
		titleText += " *"
	}
	b.WriteString(modalRow(p, w, title.Render(titleText)))
	b.WriteString("\n")

	// Top divider
	b.WriteString(s.renderHRule(w, catW, len(sepChar), "┬"))
	b.WriteString("\n")

	// Body rows
	nRight := len(s.fields[s.catIdx])
	nRows := numSettingsCats
	if nRight > nRows {
		nRows = nRight
	}
	for i := 0; i < nRows; i++ {
		leftCell := s.renderCatCell(i, catW)
		rightCell := s.renderFieldRow(i, rightW)
		row := leftCell + mb.Render(sepChar) + rightCell
		b.WriteString(modalRow(p, w, row))
		b.WriteString("\n")
	}

	// Bottom divider
	b.WriteString(s.renderHRule(w, catW, len(sepChar), "┴"))
	b.WriteString("\n")

	// Footer hint
	b.WriteString(modalRow(p, w, hint.Render(s.footerHint())))

	return placeMiddle(s.width, s.height, s.st.Modal.Render(b.String()), p)
}

// renderHRule renders a full-width horizontal rule with a junction at catW.
func (s *settingsModel) renderHRule(w, catW, sepW int, junction string) string {
	p := s.st.Palette
	mb := modalBg(p)
	left := strings.Repeat("─", catW)
	right := strings.Repeat("─", w-catW-sepW)
	return modalRow(p, w, mb.Render(left+junction+right))
}

// renderCatCell renders a left-panel cell for category index i.
func (s *settingsModel) renderCatCell(i, catW int) string {
	p := s.st.Palette
	mb := modalBg(p)
	if i >= numSettingsCats {
		return lipgloss.PlaceHorizontal(catW, lipgloss.Left, mb.Render(""),
			lipgloss.WithWhitespaceBackground(p.BgOverlay))
	}
	name := s.catNames[i]
	prefix := "  "
	if i == s.catIdx {
		prefix = "▸ "
	}
	label := prefix + truncate(name, catW-2)
	var line string
	switch {
	case i == s.catIdx && s.focus == focusCategories:
		line = s.st.Selected.Render(label)
	case i == s.catIdx:
		line = s.st.Subtitle.Inherit(mb).Render(label)
	default:
		line = mb.Render(label)
	}
	return lipgloss.PlaceHorizontal(catW, lipgloss.Left, line,
		lipgloss.WithWhitespaceBackground(p.BgOverlay))
}

// renderFieldRow renders a right-panel cell for field row i.
func (s *settingsModel) renderFieldRow(i, rightW int) string {
	p := s.st.Palette
	mb := modalBg(p)
	fields := s.fields[s.catIdx]
	if i >= len(fields) {
		return lipgloss.PlaceHorizontal(rightW, lipgloss.Left, mb.Render(""),
			lipgloss.WithWhitespaceBackground(p.BgOverlay))
	}
	f := fields[i]
	selected := s.focus == focusFields && i == s.fieldIdx

	labelW := rightW * 55 / 100
	valueW := rightW - labelW - 1
	if valueW < 6 {
		valueW = 6
	}

	labelText := " " + truncate(f.label, labelW-1)
	valueText := s.renderFieldValueRaw(f, selected, valueW)

	if selected {
		gap := labelW - lipgloss.Width(labelText)
		if gap < 0 {
			gap = 0
		}
		raw := labelText + strings.Repeat(" ", gap) + valueText
		line := s.st.Selected.Width(rightW).Render(raw)
		return lipgloss.PlaceHorizontal(rightW, lipgloss.Left, line,
			lipgloss.WithWhitespaceBackground(p.BgOverlay))
	}

	label := mb.Render(labelText)
	value := mb.Render(valueText)
	line := label + mb.Render(" ") + value
	return lipgloss.PlaceHorizontal(rightW, lipgloss.Left, line,
		lipgloss.WithWhitespaceBackground(p.BgOverlay))
}

// renderFieldValueRaw returns the plain value text for a field.
func (s *settingsModel) renderFieldValueRaw(f settingsField, selected bool, w int) string {
	switch f.kind {
	case fieldKindSelect:
		val := ""
		if f.chosen < len(f.choices) {
			val = f.choices[f.chosen]
		}
		text := truncate(val, w-4)
		if selected {
			return text + " ←→"
		}
		return text

	case fieldKindToggle:
		if f.on {
			return "✓ on"
		}
		return "  off"

	case fieldKindButton:
		return "[" + truncate(f.label, w-2) + "]"

	case fieldKindReadOnly:
		return truncate(f.display, w)
	}
	return ""
}

func (s *settingsModel) footerHint() string {
	if s.pendingDiscard {
		return s.str.Settings.HintDiscard
	}
	if s.dirty {
		return s.str.Settings.HintDirty
	}
	if s.focus == focusFields {
		return s.str.Settings.HintFields
	}
	return s.str.Settings.HintCategories
}

func (s *settingsModel) contentWidth() int {
	w := s.width * 65 / 100
	if w < 50 {
		w = 50
	}
	if w > 100 {
		w = 100
	}
	return w
}
